version: "3.7"

services:
  access-control:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      PORT: 80
      HTTPS_ENABLED: "false"
      HTTPS_CA: none
      HTTPS_PEM: also_none
      DB_HOST: db
      DB_USERNAME: accesscontrol
      DB_PASSWORD: Password123!
      DB_NAME: hackspace

  db:
    image: mysql:8
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: accesscontrol
      MYSQL_PASSWORD: Password123!
      MYSQL_DATABASE: hackspace
